-- Tables 
CREATE TABLE CITY(
	City_Name VARCHAR(50) NOT NULL,
	City_State VARCHAR(50) NOT NULL,
	Population INT UNSIGNED NOT NULL,
	PRIMARY KEY (City_Name, City_State));
CREATE TABLE STORE(
	Store_Number VARCHAR(10) NOT NULL,
	Phone_Number VARCHAR(30) NOT NULL,
	Street_Address VARCHAR(250) NOT NULL,
	City_Name VARCHAR(50) NOT NULL,
	City_State VARCHAR(50) NOT NULL,
	PRIMARY KEY (Store_Number),
	FOREIGN KEY (City_Name, City_State) REFERENCES CITY (City_Name, City_State));
CREATE Table Date(
	Date DATE NOT NULL,
    PRIMARY KEY (Date));
CREATE TABLE MEMBERSHIP(
	Member_ID VARCHAR(10) NOT NULL,
	Membership_Type ENUM('Yellow Jacket', 'Giant Hornet') NOT NULL,
	Date DATE NOT NULL,
	Store_Number VARCHAR(10) NOT NULL,
	PRIMARY KEY (Member_ID),
    FOREIGN KEY (Date) REFERENCES Date (Date),
	FOREIGN KEY (Store_Number) REFERENCES STORE (Store_Number));
CREATE TABLE MANUFACTURER(
	Manufacturer_Name VARCHAR(50) NOT NULL,
	Maximum_Discount DECIMAL(4,2) UNSIGNED NULL,
	PRIMARY KEY (Manufacturer_Name));
CREATE TABLE CATEGORY(
	Category_Name VARCHAR(50) NOT NULL,
	PRIMARY KEY (Category_Name));
CREATE TABLE PRODUCT(
	PID VARCHAR(50) NOT NULL,
	Product_Name VARCHAR(50) NOT NULL,
	Retail_Price DECIMAL(16,2) UNSIGNED NOT NULL,
	Manufacturer_Name VARCHAR(50) NOT NULL,
	PRIMARY KEY (PID),
	FOREIGN KEY (Manufacturer_Name) REFERENCES MANUFACTURER (Manufacturer_Name));
CREATE TABLE ON_SALE(
	PID VARCHAR(50) NOT NULL,
	Date DATE NOT NULL,
	Discount DECIMAL(4,2) UNSIGNED NOT NULL,
	PRIMARY KEY (PID, Date),
    FOREIGN KEY (Date) REFERENCES Date (Date),
	FOREIGN KEY (PID) REFERENCES PRODUCT (PID));
CREATE TABLE CATEGORY_OF(
	PID VARCHAR(50) NOT NULL,
	Category_Name VARCHAR(50) NOT NULL,
    PRIMARY KEY (PID, Category_Name),
	FOREIGN KEY (PID) REFERENCES PRODUCT (PID),
	FOREIGN KEY (Category_Name) REFERENCES CATEGORY (Category_Name));
CREATE TABLE HOLIDAY(
	Holiday_Name VARCHAR(50) NOT NULL,
	Date DATE NOT NULL,
	PRIMARY KEY (Date),
    FOREIGN KEY (Date) REFERENCES DATE (Date));
CREATE TABLE SOLD(
	Store_Number VARCHAR(10) NOT NULL,
	Date DATE NOT NULL,
	PID VARCHAR(50) NOT NULL,
	Unit_Quantity INT UNSIGNED NOT NULL,
	PRIMARY KEY (Store_Number, Date, PID),
	FOREIGN KEY (Store_Number) REFERENCES STORE (Store_Number),
    FOREIGN KEY (Date) REFERENCES DATE (Date),
	FOREIGN KEY (PID) REFERENCES PRODUCT (PID));